apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: gitlab
  creationTimestamp: "2024-02-15T08:30:04Z"
  generation: 5
  labels:
    app: toolbox
    app.kubernetes.io/managed-by: Helm
    chart: toolbox-7.9.1
    heritage: Helm
    release: gitlab
  name: gitlab-toolbox
  namespace: gitlab
  resourceVersion: "454465"
  uid: d6389b02-7c00-422b-bd4e-b046432b1b0b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: toolbox
      release: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: d1af15e6027c04d1d46b3d21e1c665ef55c8a1a7efbe796969c841ccb068586a
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      creationTimestamp: null
      labels:
        app: toolbox
        chart: toolbox-7.9.1
        heritage: Helm
        release: gitlab
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: gitaly
                  release: gitlab
              topologyKey: kubernetes.io/hostname
            weight: 1
      automountServiceAccountToken: false
      containers:
      - args:
        - /bin/bash
        - -c
        - cp -v -r -L /etc/gitlab/.s3cfg $HOME/.s3cfg && while sleep 3600; do :; done
        env:
        - name: ARTIFACTS_BUCKET_NAME
          value: gitlab-artifacts
        - name: REGISTRY_BUCKET_NAME
          value: registry
        - name: LFS_BUCKET_NAME
          value: git-lfs
        - name: UPLOADS_BUCKET_NAME
          value: gitlab-uploads
        - name: PACKAGES_BUCKET_NAME
          value: gitlab-packages
        - name: EXTERNAL_DIFFS_BUCKET_NAME
          value: gitlab-mr-diffs
        - name: TERRAFORM_STATE_BUCKET_NAME
          value: gitlab-terraform-state
        - name: CI_SECURE_FILES_BUCKET_NAME
          value: gitlab-ci-secure-files
        - name: BACKUP_BUCKET_NAME
          value: gitlab-backups
        - name: BACKUP_BACKEND
          value: s3
        - name: TMP_BUCKET_NAME
          value: tmp
        - name: PAGES_BUCKET_NAME
          value: gitlab-pages
        - name: GITALY_FEATURE_DEFAULT_ON
          value: "1"
        - name: ENABLE_BOOTSNAP
          value: "1"
        - name: CONFIG_TEMPLATE_DIRECTORY
          value: /var/opt/gitlab/templates
        - name: CONFIG_DIRECTORY
          value: /srv/gitlab/config
        - name: SOME_KEY
          value: map[GITLAB_LOGGER_TRUNCATE_LOGS:true]
        image: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee:v16.9.1
        imagePullPolicy: IfNotPresent
        name: toolbox
        resources:
          requests:
            cpu: 50m
            memory: 350M
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/gitlab/templates
          name: toolbox-config
        - mountPath: /etc/krb5.conf
          name: toolbox-config
          subPath: krb5.conf
        - mountPath: /srv/gitlab/config/initializers/smtp_settings.rb
          name: toolbox-config
          subPath: smtp_settings.rb
        - mountPath: /etc/gitlab
          name: toolbox-secrets
          readOnly: true
        - mountPath: /srv/gitlab/config/secrets.yml
          name: toolbox-secrets
          subPath: rails-secrets/secrets.yml
        - mountPath: /srv/gitlab/tmp
          name: toolbox-tmp
        - mountPath: /etc/ssl/certs/
          name: etc-ssl-certs
          readOnly: true
        - mountPath: /etc/pki/ca-trust/extracted/pem
          name: etc-pki-ca-trust-extracted-pem
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - env:
        - name: SOME_KEY
          value: map[GITLAB_LOGGER_TRUNCATE_LOGS:true]
        image: registry.gitlab.com/gitlab-org/build/cng/certificates:v16.9.1
        imagePullPolicy: IfNotPresent
        name: certificates
        resources:
          requests:
            cpu: 50m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: etc-ssl-certs
        - mountPath: /etc/pki/ca-trust/extracted/pem
          name: etc-pki-ca-trust-extracted-pem
        - mountPath: /usr/local/share/ca-certificates
          name: custom-ca-certificates
          readOnly: true
      - command:
        - sh
        - /config/configure
        env:
        - name: SOME_KEY
          value: map[GITLAB_LOGGER_TRUNCATE_LOGS:true]
        image: registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.9.1
        imagePullPolicy: IfNotPresent
        name: configure
        resources:
          requests:
            cpu: 50m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: toolbox-config
          readOnly: true
        - mountPath: /init-config
          name: init-toolbox-secrets
          readOnly: true
        - mountPath: /init-secrets
          name: toolbox-secrets
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: toolbox-config
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: gitlab-toolbox
      - emptyDir: {}
        name: toolbox-tmp
      - name: init-toolbox-secrets
        projected:
          defaultMode: 256
          sources:
          - secret:
              items:
              - key: secrets.yml
                path: rails-secrets/secrets.yml
              name: gitlab-rails-secret
          - secret:
              items:
              - key: secret
                path: shell/.gitlab_shell_secret
              name: gitlab-gitlab-shell-secret
          - secret:
              items:
              - key: gitaly-token
                path: gitaly/gitaly_token
              name: gitlab-gitaly
          - secret:
              items:
              - key: redis-password
                path: redis/redis-password
              name: gitlab-redis
          - secret:
              items:
              - key: postgresql-password
                path: postgres/psql-password-ci
              name: gitlab-postgresql-password
          - secret:
              items:
              - key: postgresql-password
                path: postgres/psql-password-main
              name: gitlab-postgresql-password
          - secret:
              items:
              - key: registry-auth.key
                path: registry/gitlab-registry.key
              name: gitlab-registry-secret
          - secret:
              items:
              - key: secret
                path: registry/notificationSecret
              name: gitlab-registry-notification
          - secret:
              items:
              - key: shared_secret
                path: pages/secret
              name: gitlab-gitlab-pages-secret
          - secret:
              items:
              - key: kas-key
                path: kas/.gitlab_kas_secret
              name: gitlab-kas
          - secret:
              items:
              - key: suggested_reviewers_secret
                path: suggested_reviewers/.gitlab_suggested_reviewers_secret
              name: gitlab-gitlab-suggested-reviewers
          - secret:
              items:
              - key: gitlab_username
                path: zoekt/.gitlab_zoekt_username
              - key: gitlab_password
                path: zoekt/.gitlab_zoekt_password
              name: gitlab-zoekt-basicauth
              optional: true
          - secret:
              items:
              - key: accesskey
                path: minio/accesskey
              - key: secretkey
                path: minio/secretkey
              name: gitlab-minio-secret
          - secret:
              items:
              - key: password
                path: smtp/smtp-password
              name: smtp-password
      - emptyDir:
          medium: Memory
        name: toolbox-secrets
      - emptyDir:
          medium: Memory
        name: etc-ssl-certs
      - emptyDir:
          medium: Memory
        name: etc-pki-ca-trust-extracted-pem
      - name: custom-ca-certificates
        projected:
          defaultMode: 288
          sources:
          - secret:
              items:
              - key: cfssl_ca
                path: cfssl_ca.crt
              name: gitlab-wildcard-tls-ca
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-22T01:24:32Z"
    lastUpdateTime: "2024-02-22T01:24:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-02-15T08:30:04Z"
    lastUpdateTime: "2024-02-22T01:24:32Z"
    message: ReplicaSet "gitlab-toolbox-594cd8dc6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
