# -- confiure the used image
image:
  # -- used image repository
  repository: "registry.gitlab.com/gitlab-org/cluster-integration/gitlab-agent/agentk"
  # -- set the `pullPolicy`
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "v16.9.0-rc1"

# -- Optionally set `imagePullSecrets`
imagePullSecrets: []
# -- Override the default chart name
nameOverride: ""
# -- Override the full chart name
fullnameOverride: ""

# -- set numer of replicas
replicas: 2
# -- set maxSurge for rolling update
maxSurge: 1
# -- set maxUnavailable for rolling update
maxUnavailable: 0

# -- rbac settings
rbac:
  # -- Specifies whether RBAC resources should be created
  create: true
  # -- Set to a rolename to use existing role.
  # @default -- cluster-admin
  useExistingRole:

# -- serviceAccount settings
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # @default -- name is generated using the fullname template
  name:

# -- set podSecurityContext
# Example: `fsGroup: 2000`
podSecurityContext: {}

# -- set securityContext
# Example
# `{ "capabilities": { "drop": [ "ALL" ] }, "readOnlyRootFilesystem": true, "runAsNonRoot": true, "runAsUser": 1000 }`
securityContext: {}

# -- set podAnnotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8080"

serviceMonitor:
  # -- Specifies whether to create a ServiceMonitor resource for collecting Prometheus metrics
  enabled: false

# -- configure the agent
config:
  # -- The user-facing URL for the in-cluster `agentk`
  kasAddress: 'wss://kas.192-168-1-217.nip.io'
  # -- add kas-headers
  # Example:
  # `[ "Cookie: gitlab-canary" ]`
  kasHeaders: []
  # -- put your agent token here
  token: glagent-RtgfrUshdiGgdB1VjmYyHHCqkhWz_68t7fw_ZtMK3qVohypuow
  # -- name of the secret storing the token
  secretName:
  # -- Deprecated: use `config.kasCaCert` instead. PEM certificate file to use to verify config.kasAddress. Useful if config.kasAddress is self-signed. See https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/issues/451
  caCert: |
    -----BEGIN CERTIFICATE-----
    MIIFTDCCAzSgAwIBAgIUGXE6m+zHmWGBXyoK3eONCKtToAIwDQYJKoZIhvcNAQEN
    BQAwPjEPMA0GA1UEChMGZ2l0bGFiMQ8wDQYDVQQLEwZnaXRsYWIxGjAYBgNVBAMT
    EUdpdExhYiBIZWxtIENoYXJ0MB4XDTI0MDIxNDA1MDkwMFoXDTI5MDIxMjA1MDkw
    MFowPjEPMA0GA1UEChMGZ2l0bGFiMQ8wDQYDVQQLEwZnaXRsYWIxGjAYBgNVBAMT
    EUdpdExhYiBIZWxtIENoYXJ0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
    AgEA7ScXmkrb+jFHr0RDUVjcIrrAcYO0twXqcCBRF6bGySJIupVgZDjt8T/DONbO
    00Rb0uNBuCr6NyNMX6jkmoOaJ+jgJ7dGV4Tx3LFRarwVVI1c5BH2nujvIGs/mc/4
    wbVOlu6Z8FGVV3015GhQUIAFoDcZyVHBPkjbPV7rvacEX6UgT/x636/QTR5OSneH
    MQtNVtW3nca0+uT0ke4uKtspkqwQKArUHAzuRkmrSDjCmYQ9TK27ldJgd1uK7tur
    VdBZOmBFEwd9FXiHd2Yzo3PjJ2NwcvB2Zd0iF09o4Ws8WmxnvDXEUmpKkRGFuuk6
    dbbq5unSKhFlV6LhTFamnj7BhUGVUBKUrq9F9CTb6Ayein3rp9YLwTWzJt0Gb6EL
    JJkpUhVDtz8x8lY+JJiKEDU9Bir0/H0ILkfZzLq03e0nI8+1PNGKEAlQ6nCx9lBr
    jHuYltdJfPjLd/m5Zx/xgFOgSkVq2C02e/fSplb+6rklkhQMzWmzNm0VsgIvDFrt
    RCsF8GvmYC5Qc+1kWo1dfhRenyULSQJet1EXopLDjF1QCAMu9zMR1RgO4ELUkJi3
    ZU2pMSiAnnlPZIGx6u5B4YvWJmaumouRdBeankWhOOjBR9Yv0JOUrhe5KITCaO0B
    fa2UFnXHaPkJSF8WXFd1laDarxZnnBY7OPF0vpTKBXGnZqECAwEAAaNCMEAwDgYD
    VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCiDB6ef3vTl
    qKGWw5k9CvpD/9kwMA0GCSqGSIb3DQEBDQUAA4ICAQBqjeRGGoDYJMLgrai7VrHV
    19Y00eaJmqN8kCMTmRUhUtlUFdPy83od+UMVGMMi7ZUB27amJxRb1KaYMj+qL5kJ
    MJpABDWCWBAVjkiopQlcwyRU+oukP4euQPgt4rryiXbsy/9zTYnSl3Nc+SQ8Db8N
    ci4+yOHogObKaUmD+k2YgoDrMHYMH/Gx6RHFeojBJEB+7IkJu2PV0cnpj3NUlWRV
    n9QqWH4SwuHEz4heFHMf5rrVtkHzDouc52XnPP/ynQDOqwuFuPmTYzwKIJlk7Ta0
    Jw0FjsoD2op5qZZolRjtF2trkrY1jW/EVHD54B1IBu2W99wIBL98UXTmARXSNudy
    FdsdaNVsSQm5QTCQqhmNcfw97ixGvCwTakxMquDdsahm8inLExq1wwH/HhpRpfme
    j3ZtbxWvkE8xJ/gajZmIwC0PDT51Stw+a8A66NrXMtdGINV9D7LPQh+2oLA2eGEg
    U5ApukBSrD5hYmvVQP/0kAZkRrcoXs/v1mfDBJU6NiuzZBSSFco4tyaVjg2OreBI
    L5EVWU/J94BvhXcQEWlgooaN+DusjfZAvBR4JUFV2/922yqtUrhK0SJEsIr+Motu
    dvNJlagsRxQESpYGAgUTjQzc/Ifq/IiAdeGlhGDJhKjkgGT8oz9M2PFNwc7Hv2Js
    YiQjg9IgofUz8AnG5196tg==
    -----END CERTIFICATE-----

  kasCaCert:

  observability:
    enabled: true
    # -- Application-level TLS configuration for the observability service
    tls:
      # -- enable application-level TLS for the observability service
      enabled: false
      # -- Public key for the TLS certificate for the observability service
      cert:
      # -- Private key for the TLS certificate for the observability service
      key:
      secret:
        # -- when true, creates a certificate with values cert and key from  for the observability service
        create: false
        # -- secret name for the observability service
        name: "gitlab-agent-observability"

  operational_container_scanning:
    # -- enables automatic RBAC creation for the operational container scanning feature
    enabled: true

# -- Add additional environment settings to the pod. Can be useful in
# proxy environments
extraEnv: []

# -- Add additional args settings to the pod.
extraArgs: []

# -- Add extra volume mounts
extraVolumeMounts: []

# -- Add extra volumes
extraVolumes: []

# -- set resource parmeters
# Example:
# `{ "limits": { "cpu": "100m", "memory": "128Mi" }, "requests": { "cpu": "100m", "memory": "128Mi" }}`
resources: {}

# -- nodeSelector
nodeSelector: {}

# -- tolerations
tolerations: []

# -- set affinity
affinity: {}

# -- set priorityClassName
priorityClassName: ""

# -- list of hosts and IPs that will be injected into the pod's hosts file
# Example:
# `[{ "ip": "127.0.0.1", "hostnames": [ "foo.local", "bar.local" ]}, { "ip": "10.1.2.3", "hostnames": [ "foo.remote", "bar.remote" ]}]`
hostAliases: {}
# -- Labels to be added to each agent pod
# Example:
# `role: developer`
podLabels: {}

# -- Additional labels to be added to all created objects
additionalLabels: {}

# -- Optional initContainers definition
initContainers: []

# --
# Show the last 80 lines or 2048 bytes (whichever is smaller) of pod logs in kubectl describe output when
# container exits with non-zero exit code # Useful for when pod logs are cycled out of a node post-crash
# before an operator can capture the logs
# Valid values are 'File' which is the Kubernetes API default, or 'FallbackToLogsOnError'
# See <https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/> for more information
terminationMessagePolicy: FallbackToLogsOnError
